-- Seed experts that match frontend mock IDs
-- Safe to re-run; uses upsert by expert_id

insert into experts (
  expert_id,
  name,
  role,
  organization,
  category_tags,
  service_tags,
  location,
  remote_available,
  budget_range,
  availability_status,
  average_response_time,
  rating,
  review_count,
  is_featured,
  is_verified,
  tier,
  matching_visibility,
  hourly_rate_usd,
  years_experience,
  next_available_at,
  profile_views_7d,
  clicks_7d,
  impressions_7d,
  top3_shown_24h_count,
  lead_acceptance_rate,
  successful_connection_rate,
  approved_at
)
values
  (
    'exp_ana_khan',
    'Ana Khan',
    'Operations & Growth Advisor',
    'Sentinel Advisory Group',
    array['Operations','Growth','Legal Help'],
    array['Operations Reset Plan','Business Registration','Compliance'],
    'Nassau, New Providence',
    true,
    '{"min":150,"max":400}'::jsonb,
    'available_now',
    8,
    4.9,
    18,
    true,
    true,
    'featured',
    'visible',
    180,
    12,
    now() + interval '2 hours',
    50,
    9,
    45,
    2,
    0.72,
    0.48,
    now() - interval '20 days'
  ),
  (
    'exp_daniel_cho',
    'Daniel Cho',
    'Cybersecurity & IT Response Consultant',
    'BlueTrace Labs',
    array['Cybersecurity','Systems','Personal Tech Support'],
    array['Cybersecurity Baseline Review','Incident Response','Systems Improvement Sprint'],
    'Freeport, Grand Bahama',
    true,
    '{"min":120,"max":350}'::jsonb,
    'within_48h',
    20,
    4.8,
    15,
    true,
    true,
    'featured',
    'visible',
    165,
    10,
    now() + interval '10 hours',
    70,
    10,
    65,
    4,
    0.68,
    0.41,
    now() - interval '40 days'
  ),
  (
    'exp_sofia_ramirez',
    'Sofia Ramirez',
    'Finance & Career Advisor',
    'AccessGrid Advisory',
    array['Financial Advice','Career Help','Operations'],
    array['Advice & Guidance Session','Financial Cleanup','Growth Support'],
    'Nassau, New Providence',
    true,
    '{"min":100,"max":300}'::jsonb,
    'within_48h',
    30,
    4.7,
    11,
    false,
    true,
    'verified',
    'visible',
    150,
    9,
    now() + interval '22 hours',
    25,
    4,
    15,
    1,
    0.55,
    0.33,
    now() - interval '8 days'
  )
on conflict (expert_id) do update set
  name = excluded.name,
  role = excluded.role,
  organization = excluded.organization,
  category_tags = excluded.category_tags,
  service_tags = excluded.service_tags,
  location = excluded.location,
  remote_available = excluded.remote_available,
  budget_range = excluded.budget_range,
  availability_status = excluded.availability_status,
  average_response_time = excluded.average_response_time,
  rating = excluded.rating,
  review_count = excluded.review_count,
  is_featured = excluded.is_featured,
  is_verified = excluded.is_verified,
  tier = excluded.tier,
  matching_visibility = excluded.matching_visibility,
  hourly_rate_usd = excluded.hourly_rate_usd,
  years_experience = excluded.years_experience,
  next_available_at = excluded.next_available_at,
  profile_views_7d = excluded.profile_views_7d,
  clicks_7d = excluded.clicks_7d,
  impressions_7d = excluded.impressions_7d,
  top3_shown_24h_count = excluded.top3_shown_24h_count,
  lead_acceptance_rate = excluded.lead_acceptance_rate,
  successful_connection_rate = excluded.successful_connection_rate,
  approved_at = excluded.approved_at;
